### ISSUE TITLE
Missing python dataset building script

### ISSUE THREAD

**Issue by fbottarel** [aalto-intelligent-robotics/shape_completion_network#1]
Thanks for uploading the code and the detailed instructions. I managed to get almost through everything, however I am stuck to this:
```
python build_dataset.py [-h] [--dataset-type [{train_test,debug}]]
                        [--path-to-dataset PATH_TO_DATASET]
                        [--dataset-seed DATASET_SEED]
                        [--use-default-split USE_DEFAULT_SPLIT]
```
since the `build_dataset.py` file appears to be missing in the repo. Could you please check if this is the case on your end? 

Thanks

**Comment by jsll** [comment]
You were absolutely correct. I did not include it but now it is in the datasets folder.

I will mark this resolved.

**Comment by fbottarel** [comment]
Thanks @jsll. Did you include the python script itself or the parsed list of object meshes?

**Comment by jsll** [comment]
Now I also added build_dataset.py to the datasets directory. Now everything should work
