### ISSUE TITLE
Cannot load pre-trained network weights

### ISSUE THREAD

**Issue by fbottarel** [aalto-intelligent-robotics/shape_completion_network#3]
As title says. 

After following your guide and installing everything needed, I tried to perform inference on some test data to obtain shape-completed meshes. After downloading the models as described in the README,  I ran 

`shape_completion_main.py --mode test --batch-size 1 --num-workers 1 --use-cuda 0`

Apparently, I cannot load the model (`mc_dropout_rate_0.2_lat_2000.model` downloaded in the proper directory) since I get an error at line 199 of `network_utils.py`.

```
tc.load(weight_file, map_location=hardware)
*** UnpicklingError: invalid load key, '<'.
```

@jsll Can you please help me debug this? I would really love to benchmark the pipeline against other modeling approaches we use in the lab.

**Comment by jsll** [comment]
It seemed that the file mc_dropout_rate_0.2_lat_2000.model was corrupted. Don't know why but I swapped it to an older model and now it should work. Simply remove the pre_trained_networks folder and rerun `bash download_networks.sh`. Be aware, however, that the new model file is not the fully optimized one. I will have to retrain such a model in the forthcoming future.

**Comment by fbottarel** [comment]
Thanks for looking into it. I did as you advised, however the outcome is still the same. The `torch.load()` call returns the same unpickling error, even when called from a python console. Maybe I'm doing something wrong without even noticing.

**Comment by fbottarel** [comment]
Google Drive was apparently corrupting the models at upload time. Now they are hosted and downloaded in archive form and PyTorch can load the models successfully.

**Comment by hetolin** [comment]
@fbottarel 
Hi, did you retrain the network? I found that there is no full_Dataset.yaml file in datasets/.
But in the code, it used the full_Dataset.yaml file:

def load_dataset(batch_size, num_cuda_workers, mode, debug=False, seed=100): datafile = "" if debug: datafile = "datasets/debug_Dataset.yaml" elif mode == "train": datafile = "datasets/full_Dataset.yaml" elif mode == "test": datafile = "datasets/full_test_Dataset.yaml"

There only exists objects.yaml and default_train_test_spilt.yaml in the ../datasets/
Have you solve this problem?
